/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Main.MainPage;
import appcode.Session;
import appcode.form.RoundedGradientButton;
import appcode.table.TableActionCellEditor;
import appcode.table.TableActionCellRender;
import appcode.table.TableActionEvent;
import java.awt.Image;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

public class MenuEmptyQueue extends javax.swing.JPanel {

    /**
     * Creates new form MenuHome
     */
    DefaultTableModel model;
    Connection conn = new Koneksi().connect();
    public MenuEmptyQueue() {
        initComponents();

        loadDataWaiting();
        tblDataWaiting.fixTable(jScrollPane2);

        jTabbedPane1.addChangeListener((ChangeEvent e) -> {
            int selectedIndex = jTabbedPane1.getSelectedIndex();
            switch (selectedIndex) {
                case 0:
                    loadDataWaiting();
                    tblDataWaiting.fixTable(jScrollPane2);
                    break;
                case 1:
                    loadDataAssigned();
                    tblDataAssigned.fixTable(jScrollPane1);
                    break;
                case 2:
                    loadDataCancelled();
                    tblDataCancelled.fixTable(jScrollPane3);
                    break;
                default:
                    break;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelWaiting = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataWaiting = new appcode.table.TableDark();
        btnAddWaiting = new RoundedGradientButton("Tambah");
        btnReport1 = new RoundedGradientButton("Laporan");
        txtSearchWaiting = new appcode.form.CustomTextField();
        panelAssigned = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataAssigned = new appcode.table.TableDark();
        btnAddAssigned = new RoundedGradientButton("Tambah");
        btnReport = new RoundedGradientButton("Laporan");
        txtSearchAssigned = new appcode.form.CustomTextField();
        panelCancelled = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDataCancelled = new appcode.table.TableDark();
        btnAddCancelled = new RoundedGradientButton("Tambah");
        btnReport2 = new RoundedGradientButton("Laporan");
        txtSearchCancelled = new appcode.form.CustomTextField();

        setBackground(new java.awt.Color(45, 48, 51));

        jTabbedPane1.setForeground(new java.awt.Color(204, 102, 0));

        panelWaiting.setBackground(new java.awt.Color(45, 48, 51));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Empty Queue");

        tblDataWaiting.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDataWaiting);

        btnAddWaiting.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddWaiting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddWaiting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWaitingActionPerformed(evt);
            }
        });

        btnReport1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport1ActionPerformed(evt);
            }
        });

        txtSearchWaiting.setBackground(new java.awt.Color(138, 138, 138));
        txtSearchWaiting.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchWaiting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchWaiting.setPlaceholder("Cari");
        txtSearchWaiting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchWaitingActionPerformed(evt);
            }
        });
        txtSearchWaiting.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchWaitingKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelWaitingLayout = new javax.swing.GroupLayout(panelWaiting);
        panelWaiting.setLayout(panelWaitingLayout);
        panelWaitingLayout.setHorizontalGroup(
            panelWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWaitingLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(671, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWaitingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelWaitingLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSearchWaiting, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddWaiting, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelWaitingLayout.setVerticalGroup(
            panelWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWaitingLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearchWaiting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReport1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddWaiting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("WAITING", panelWaiting);

        panelAssigned.setBackground(new java.awt.Color(45, 48, 51));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Empty Queue");

        tblDataAssigned.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDataAssigned);

        btnAddAssigned.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddAssigned.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddAssigned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAssignedActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        txtSearchAssigned.setBackground(new java.awt.Color(138, 138, 138));
        txtSearchAssigned.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchAssigned.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchAssigned.setPlaceholder("Cari");
        txtSearchAssigned.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchAssignedKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelAssignedLayout = new javax.swing.GroupLayout(panelAssigned);
        panelAssigned.setLayout(panelAssignedLayout);
        panelAssignedLayout.setHorizontalGroup(
            panelAssignedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssignedLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAssignedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAssignedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelAssignedLayout.createSequentialGroup()
                        .addGap(0, 437, Short.MAX_VALUE)
                        .addComponent(txtSearchAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelAssignedLayout.setVerticalGroup(
            panelAssignedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssignedLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAssignedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAssignedLayout.createSequentialGroup()
                        .addGroup(panelAssignedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearchAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ASSIGNED", panelAssigned);

        panelCancelled.setBackground(new java.awt.Color(45, 48, 51));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Empty Queue");

        tblDataCancelled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblDataCancelled);

        btnAddCancelled.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddCancelled.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCancelled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCancelledActionPerformed(evt);
            }
        });

        btnReport2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReport2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport2ActionPerformed(evt);
            }
        });

        txtSearchCancelled.setBackground(new java.awt.Color(138, 138, 138));
        txtSearchCancelled.setForeground(new java.awt.Color(255, 255, 255));
        txtSearchCancelled.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchCancelled.setPlaceholder("Cari");
        txtSearchCancelled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCancelledKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelCancelledLayout = new javax.swing.GroupLayout(panelCancelled);
        panelCancelled.setLayout(panelCancelledLayout);
        panelCancelledLayout.setHorizontalGroup(
            panelCancelledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelledLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCancelledLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCancelledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(panelCancelledLayout.createSequentialGroup()
                        .addGap(0, 437, Short.MAX_VALUE)
                        .addComponent(txtSearchCancelled, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddCancelled, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReport2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCancelledLayout.setVerticalGroup(
            panelCancelledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelledLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCancelledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCancelledLayout.createSequentialGroup()
                        .addGroup(panelCancelledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReport2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddCancelled, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearchCancelled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CANCELLED", panelCancelled);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Petak");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAssignedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAssignedActionPerformed
        // TODO add your handling code here:
        setupDialog().setVisible(true);
    }//GEN-LAST:event_btnAddAssignedActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            HashMap parameter = new HashMap();
            parameter.put("USER",Session.getNama());
            File report_file = new File("src/laporan/LaporanBlokMakam.jasper");
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (JRException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnAddWaitingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWaitingActionPerformed
        // TODO add your handling code here:
        setupDialog().setVisible(true);
    }//GEN-LAST:event_btnAddWaitingActionPerformed

    private void btnReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            HashMap parameter = new HashMap();
            parameter.put("USER",Session.getNama());
            File report_file = new File("src/laporan/LaporanLokasiMakam.jasper");
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (JRException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReport1ActionPerformed

    private void btnAddCancelledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCancelledActionPerformed
        // TODO add your handling code here:
        setupDialog().setVisible(true);
    }//GEN-LAST:event_btnAddCancelledActionPerformed

    private void btnReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            HashMap parameter = new HashMap();
            parameter.put("USER",Session.getNama());
            File report_file = new File("src/laporan/LaporanPetakMakam.jasper");
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (JRException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReport2ActionPerformed

    private void txtSearchWaitingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchWaitingKeyReleased
        // TODO add your handling code here:
        loadDataWaiting();
    }//GEN-LAST:event_txtSearchWaitingKeyReleased

    private void txtSearchAssignedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchAssignedKeyReleased
        // TODO add your handling code here:
        loadDataAssigned();
    }//GEN-LAST:event_txtSearchAssignedKeyReleased

    private void txtSearchCancelledKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCancelledKeyReleased
        // TODO add your handling code here:
        loadDataCancelled();
    }//GEN-LAST:event_txtSearchCancelledKeyReleased

    private void txtSearchWaitingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchWaitingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchWaitingActionPerformed

    private void loadDataWaiting() {
        String sql =
            "SELECT q.ID, t.PlateNumber, d.DriverName, q.Note, q.ReportedAt, " +
            "q.PhotoUrl, q.Status, q.AssignedDeliveryCode, q.AssignedAt, q.UpdatedAt " +
            "FROM Truck_Empty_Queue q " +
            "INNER JOIN Trucks t ON q.TruckID = t.ID " +
            "INNER JOIN Drivers d ON q.DriverID = d.ID " +
            "WHERE q.Status = 'WAITING' ";

        String search = txtSearchWaiting.getText();
        if (!search.isEmpty()) {
            sql += "AND (t.PlateNumber LIKE '%" + search + "%' OR " +
                   "d.DriverName LIKE '%" + search + "%' OR " +
                   "q.Note LIKE '%" + search + "%') ";
        }

        sql += "ORDER BY q.UpdatedAt DESC";

        // Header tabel
        Object[] Header = { "No", "Action", "Plat", "Driver", "Note", "Tanggal Kosong",
                            "Bukti Kosong", "Status", "Assigned Delivery Code", "Tanggal Assigned", "Updated At" };

        model = new DefaultTableModel(null, Header) {
            @Override
            public Class<?> getColumnClass(int column) {
                if (column == 6) return ImageIcon.class; // kolom Bukti Kosong
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 1; // hanya kolom Action (Edit/Delete) yang bisa diklik
            }
        };

        tblDataWaiting.setModel(model);
        tblDataWaiting.setRowHeight(80); // tinggi row untuk image

        try {
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            int num = 1;

            while (rs.next()) {
                // Ambil field
                String tanggalKosong = rs.getString("ReportedAt");
                String photoPath = rs.getString("PhotoUrl");
                String status = rs.getString("Status");
                String assignedCode = rs.getString("AssignedDeliveryCode");
                String tanggalAssigned = rs.getString("AssignedAt");

                // Image preview
                ImageIcon imageIcon = null;
                if (photoPath != null && !photoPath.isEmpty()) {
                    Image img = new ImageIcon(photoPath).getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
                    imageIcon = new ImageIcon(img);
                }

                Object[] data = {
                    num,
                    rs.getString("ID"),             // Action
                    rs.getString("PlateNumber"),
                    rs.getString("DriverName"),
                    rs.getString("Note"),
                    tanggalKosong,
                    imageIcon,
                    status,
                    assignedCode,
                    tanggalAssigned,
                    rs.getString("UpdatedAt")
                };

                model.addRow(data);
                num++;
            }

            // Action Edit/Delete
            TableActionEvent actionEvent = new TableActionEvent() {
                @Override
                public void onEdit(int row) {
                    DialogEmptyQueueAddEdit dialog = setupDialog();
                    dialog.setData(Integer.parseInt(model.getValueAt(row, 1).toString()));
                    dialog.setVisible(true);
                }

                @Override
                public void onDelete(int row) {
                    int confirm = JOptionPane.showConfirmDialog(
                            null,
                            "Konfirmasi hapus antrian?",
                            "Warning",
                            JOptionPane.YES_NO_OPTION
                    );

                    if (confirm == JOptionPane.YES_OPTION) {
                        String queueId = model.getValueAt(row, 1).toString();
                        try {
                            String sqlDelete = "DELETE FROM Truck_Empty_Queue WHERE ID = ?";
                            PreparedStatement ps = conn.prepareStatement(sqlDelete);
                            ps.setString(1, queueId);
                            ps.executeUpdate();
                            ps.close();

                            JOptionPane.showMessageDialog(null, "Queue Berhasil Dihapus");
                            loadDataWaiting();

                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "Queue Gagal Dihapus: " + e.getMessage());
                        }
                    }
                }
            };

            tblDataWaiting.getColumnModel().getColumn(1).setCellRenderer(new TableActionCellRender());
            tblDataWaiting.getColumnModel().getColumn(1).setCellEditor(new TableActionCellEditor(actionEvent));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }


    private DialogEmptyQueueAddEdit setupDialog() {
        DialogEmptyQueueAddEdit dialog = new DialogEmptyQueueAddEdit(null, true);
        dialog.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {

            }

            @Override
            public void windowClosing(WindowEvent e) {

            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadDataWaiting();
            }

            @Override
            public void windowIconified(WindowEvent e) {

            }

            @Override
            public void windowDeiconified(WindowEvent e) {

            }

            @Override
            public void windowActivated(WindowEvent e) {

            }

            @Override
            public void windowDeactivated(WindowEvent e) {

            }
        });
        return dialog;
    }

   private void loadDataAssigned() {
        String sql =
            "SELECT q.ID, t.PlateNumber, d.DriverName, q.Note, q.ReportedAt, " +
            "q.PhotoUrl, q.Status, q.AssignedDeliveryCode, q.AssignedAt, q.UpdatedAt " +
            "FROM Truck_Empty_Queue q " +
            "INNER JOIN Trucks t ON q.TruckID = t.ID " +
            "INNER JOIN Drivers d ON q.DriverID = d.ID " +
            "WHERE q.Status = 'ASSIGNED' ";

        String search = txtSearchAssigned.getText();
        if (!search.isEmpty()) {
            sql += "AND (t.PlateNumber LIKE '%" + search + "%' OR " +
                   "d.DriverName LIKE '%" + search + "%' OR " +
                   "q.Note LIKE '%" + search + "%') ";
        }

        sql += "ORDER BY q.UpdatedAt DESC";

        Object[] Header = { "No", "Action", "Plat", "Driver", "Note", "Tanggal Kosong",
                            "Bukti Kosong", "Status", "Assigned Delivery Code", "Tanggal Assigned", "Updated At" };

        model = new DefaultTableModel(null, Header) {
            @Override
            public Class<?> getColumnClass(int column) {
                if (column == 6) return ImageIcon.class; // kolom Bukti Kosong
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 1; // hanya kolom Action yang bisa diklik
            }
        };

        tblDataAssigned.setModel(model);
        tblDataAssigned.setRowHeight(80); // tinggi row untuk image

        try {
            Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql);
            int num = 1;

            while (rs.next()) {
                String tanggalKosong = rs.getString("ReportedAt");
                String photoPath = rs.getString("PhotoUrl");
                String status = rs.getString("Status");
                String assignedCode = rs.getString("AssignedDeliveryCode");
                String tanggalAssigned = rs.getString("AssignedAt");

                // Image preview
                ImageIcon imageIcon = null;
                if (photoPath != null && !photoPath.isEmpty()) {
                    Image img = new ImageIcon(photoPath).getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
                    imageIcon = new ImageIcon(img);
                }

                Object[] data = {
                    num,
                    rs.getString("ID"),             // Action
                    rs.getString("PlateNumber"),
                    rs.getString("DriverName"),
                    rs.getString("Note"),
                    tanggalKosong,
                    imageIcon,
                    status,
                    assignedCode,
                    tanggalAssigned,
                    rs.getString("UpdatedAt")
                };

                model.addRow(data);
                num++;
            }

            // Action Edit/Delete
            TableActionEvent actionEvent = new TableActionEvent() {
                @Override
                public void onEdit(int row) {
                    DialogEmptyQueueAddEdit dialog = setupDialog();
                    dialog.setData(Integer.parseInt(model.getValueAt(row, 1).toString()));
                    dialog.setVisible(true);
                }

                @Override
                public void onDelete(int row) {
                    int confirm = JOptionPane.showConfirmDialog(
                            null,
                            "Konfirmasi hapus antrian?",
                            "Warning",
                            JOptionPane.YES_NO_OPTION
                    );

                    if (confirm == JOptionPane.YES_OPTION) {
                        String queueId = model.getValueAt(row, 1).toString();
                        try {
                            String sqlDelete = "DELETE FROM Truck_Empty_Queue WHERE ID = ?";
                            PreparedStatement ps = conn.prepareStatement(sqlDelete);
                            ps.setString(1, queueId);
                            ps.executeUpdate();
                            ps.close();

                            JOptionPane.showMessageDialog(null, "Queue Berhasil Dihapus");
                            loadDataAssigned();

                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "Queue Gagal Dihapus: " + e.getMessage());
                        }
                    }
                }
            };

            tblDataAssigned.getColumnModel().getColumn(1).setCellRenderer(new TableActionCellRender());
            tblDataAssigned.getColumnModel().getColumn(1).setCellEditor(new TableActionCellEditor(actionEvent));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void loadDataCancelled(){
        String sql =
            "SELECT q.ID, t.PlateNumber, d.DriverName, q.Note, q.UpdatedAt " +
            "FROM Truck_Empty_Queue q " +
            "INNER JOIN Trucks t ON q.TruckID = t.ID " +
            "INNER JOIN Drivers d ON q.DriverID = d.ID " +
            "WHERE q.Status = 'CANCELLED' ";

        String search = txtSearchCancelled.getText();
        if (!search.isEmpty()) {
            sql += "AND (t.PlateNumber LIKE '%" + search + "%' OR " +
                   "d.DriverName LIKE '%" + search + "%' OR " +
                   "q.Note LIKE '%" + search + "%') ";
        }

        sql += "ORDER BY q.UpdatedAt DESC";

        Object[] Header = { "No", "Action", "Plat", "Driver", "Note", "Updated At" };
        model = new DefaultTableModel(null, Header);
        tblDataCancelled.setModel(model);

        try{
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            int num = 1;

            while(hasil.next()){
                String[] data = {
                    Integer.toString(num),           // No
                    hasil.getString("ID"),           // Action (ID)
                    hasil.getString("PlateNumber"),  // Plat
                    hasil.getString("DriverName"),   // Driver
                    hasil.getString("Note"),         // Note
                    hasil.getString("UpdatedAt")     // Updated At
                };
                model.addRow(data);
                num++;
            }

            TableActionEvent actionEvent = new TableActionEvent() {
                @Override
                public void onEdit(int row) {
                    DialogEmptyQueueAddEdit dialog = setupDialog();
                    dialog.setData(Integer.parseInt(model.getValueAt(row, 1).toString()));
                    dialog.setVisible(true);
                }

                @Override
                public void onDelete(int row) {
                    int confirm = JOptionPane.showConfirmDialog(
                            null,
                            "Konfirmasi hapus antrian?",
                            "Warning",
                            JOptionPane.YES_NO_OPTION
                    );

                    if(confirm == JOptionPane.YES_OPTION){
                        String queueId = model.getValueAt(row, 1).toString();
                        try {
                            String sqlDelete = "DELETE FROM Truck_Empty_Queue WHERE ID = ?";
                            PreparedStatement ps = conn.prepareStatement(sqlDelete);
                            ps.setString(1, queueId);
                            ps.executeUpdate();
                            ps.close();

                            JOptionPane.showMessageDialog(null, "Queue Berhasil Dihapus");
                            loadDataCancelled();

                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, "Queue Gagal Dihapus: " + e.getMessage());
                        }
                    }
                }
            };

            tblDataCancelled.getColumnModel().getColumn(1).setCellRenderer(new TableActionCellRender());
            tblDataCancelled.getColumnModel().getColumn(1).setCellEditor(new TableActionCellEditor(actionEvent));

        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAssigned;
    private javax.swing.JButton btnAddCancelled;
    private javax.swing.JButton btnAddWaiting;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnReport1;
    private javax.swing.JButton btnReport2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelAssigned;
    private javax.swing.JPanel panelCancelled;
    private javax.swing.JPanel panelWaiting;
    private appcode.table.TableDark tblDataAssigned;
    private appcode.table.TableDark tblDataCancelled;
    private appcode.table.TableDark tblDataWaiting;
    private appcode.form.CustomTextField txtSearchAssigned;
    private appcode.form.CustomTextField txtSearchCancelled;
    private appcode.form.CustomTextField txtSearchWaiting;
    // End of variables declaration//GEN-END:variables
}
